---

- hosts: localhost
  connection: local
  become: false
  pre_tasks:
    - name AWS credentials | parse
      aws_credentials:
        profile: sumo

  roles:
    - role: ec2-pod2
      name: sumo-testing
      region: us-east-1
      state: absent
