#! /usr/bin/env bash
#
# small script for running the mongo docker container
#
# ./mongo-docker [data-dir]
#
#     data-dir: directory on the host filesystem on which to store the database
#               data for persistence. (default: $SD/../cache/mongo where SD is
#                                      the directory where the script is
#                                      located)
#

data_dir="$1" ; shift
if [ -z "$data_dir" ] ; then
    data_dir="$( dirname "$( dirname "$( readlink -e "$0" )" )")/cache/mongo"
else
    data_dir="$( readlink -f "$data_dir" )"
fi

mkdir -p "$( dirname "$data_dir" )"
docker run -p 27017:27017 -v "$data_dir":/data/db mongo

